import type { PublicPageSeed } from './types';

export const platformSeeds: readonly PublicPageSeed[] = [
  {
    href: "/platform/student-information-system",
    title: "Student Information System",
    kind: "platform",
    summary: "Maintain authoritative student records across the learner lifecycle while preserving programme, campus and status context.",
    focus: [
      "Student identity and lifecycle records",
      "Programme, curriculum and enrolment associations",
      "Academic standing, history and document control",
      "Data quality, permissions and audit history",
    ],
  },
  {
    href: "/platform/academics",
    title: "Academic Management",
    kind: "platform",
    summary: "Coordinate curricula, courses, calendars, sections and academic rules through reviewable institutional workflows.",
    focus: [
      "Curriculum and regulation configuration",
      "Course catalogue, credits and prerequisites",
      "Academic calendars, sections and teaching plans",
      "Approval, versioning and change governance",
    ],
  },
  {
    href: "/platform/admissions",
    title: "Admissions and Enrollment",
    kind: "platform",
    summary: "Move applicants from enquiry to verified enrolment with clear ownership across admissions, academics and finance.",
    focus: [
      "Enquiries, applications and applicant communication",
      "Document review and eligibility decisions",
      "Merit, selection and seat-allocation workflows",
      "Enrolment activation and downstream handoff",
    ],
  },
  {
    href: "/platform/finance",
    title: "Finance and Billing",
    kind: "platform",
    summary: "Manage student billing, collections, concessions, refunds and reconciliation with institution-defined financial controls.",
    focus: [
      "Fee structures, invoices and payment schedules",
      "Online and offline collection reconciliation",
      "Scholarships, concessions and sponsorships",
      "Refunds, receivables and finance reporting",
    ],
  },
  {
    href: "/platform/people",
    title: "People and HR",
    kind: "platform",
    summary: "Support employee records and workforce processes from onboarding through attendance, leave, payroll coordination and performance.",
    focus: [
      "Employee records, appointments and onboarding",
      "Attendance, leave and duty workflows",
      "Payroll inputs and statutory coordination",
      "Performance, documents and workforce reporting",
    ],
  },
  {
    href: "/platform/campus-operations",
    title: "Campus Operations",
    kind: "platform",
    summary: "Coordinate facilities and campus services through structured requests, allocations, schedules and service accountability.",
    focus: [
      "Hostel, transport and library operations",
      "Facilities, assets and preventive maintenance",
      "Visitor, gate-pass and campus-access workflows",
      "Helpdesk requests, service levels and reporting",
    ],
  },
  {
    href: "/platform/learning-management",
    title: "Learning Management",
    kind: "platform",
    summary: "Deliver structured digital learning with governed course content, activities, progress and academic feedback.",
    focus: [
      "Course content and learning-path organisation",
      "Learning activities, discussions and resources",
      "Learner progress and participation visibility",
      "Grades, feedback and completion evidence",
    ],
  },
  {
    href: "/platform/course-workspace",
    title: "Course Workspace",
    kind: "platform",
    summary: "Give each course a focused operational space for rosters, materials, communication, tasks and teaching activity.",
    focus: [
      "Course roster and section context",
      "Materials, announcements and discussions",
      "Assignment calendar and class activity",
      "Course-level progress and teaching insights",
    ],
  },
  {
    href: "/platform/live-learning",
    title: "Live Learning",
    kind: "platform",
    summary: "Plan and run synchronous teaching sessions with attendance, engagement, recordings and support context.",
    focus: [
      "Session scheduling and secure join access",
      "Live attendance and engagement signals",
      "Recordings, resources and follow-up tasks",
      "Session quality, support and exception review",
    ],
  },
  {
    href: "/platform/assignments",
    title: "Assignments and Assessments",
    kind: "platform",
    summary: "Manage assessment design, submission, evaluation and feedback with deadlines, rubrics and moderation controls.",
    focus: [
      "Assessment briefs, rubrics and outcome mapping",
      "Submission windows and late-work rules",
      "Evaluation, moderation and mark approval",
      "Feedback, rework and assessment reporting",
    ],
  },
  {
    href: "/platform/examinations",
    title: "Examinations and Results",
    kind: "platform",
    summary: "Coordinate examination planning, secure evaluation and approved result publication across programmes and campuses.",
    focus: [
      "Exam schedules, rooms and candidate planning",
      "Question-paper and evaluation security",
      "Moderation, approval and result processing",
      "Publication, revaluation and grievance workflows",
    ],
  },
  {
    href: "/platform/faculty-portal",
    title: "Faculty Tools",
    kind: "platform",
    summary: "Bring teaching schedules, attendance, grading, advisee support and assigned academic actions into one faculty workspace.",
    focus: [
      "Timetable, workload and course responsibilities",
      "Attendance and teaching-session actions",
      "Assessment grading and student feedback",
      "Advisee support, approvals and academic follow-up",
    ],
  },
  {
    href: "/platform/student-portal",
    title: "Student Portal",
    kind: "platform",
    summary: "Give students one secure place for learning, attendance, results, fees, documents and campus-service actions.",
    focus: [
      "Timetable, courses and attendance visibility",
      "Assignments, examinations and results",
      "Fees, receipts and institutional documents",
      "Requests, notifications and student services",
    ],
  },
  {
    href: "/platform/mobile",
    title: "Mobile App",
    kind: "platform",
    summary: "Extend essential CampusOS workflows to mobile devices with secure access, notifications and resilient user experience.",
    focus: [
      "Mobile access to priority student and staff tasks",
      "Push notifications and action reminders",
      "Digital identity and campus-service access",
      "Low-bandwidth and device-aware experience",
    ],
  },
  {
    href: "/platform/community",
    title: "Community and Messaging",
    kind: "platform",
    summary: "Deliver targeted institutional communication with audience controls, moderated spaces and delivery visibility.",
    focus: [
      "Targeted announcements and audience selection",
      "Groups, channels and community spaces",
      "Moderation, escalation and policy controls",
      "Delivery, acknowledgement and read-status insight",
    ],
  },
  {
    href: "/platform/digital-id",
    title: "Digital Campus ID",
    kind: "platform",
    summary: "Support institution-issued digital identity for authorised access to services, locations and campus experiences.",
    focus: [
      "Identity proofing and credential issuance",
      "QR or barcode-based service verification",
      "Access-policy and entitlement checks",
      "Credential lifecycle, suspension and revocation",
    ],
  },
  {
    href: "/platform/parent-portal",
    title: "Parent Portal",
    kind: "platform",
    summary: "Provide authorised parents or guardians with appropriate academic, attendance, fee and communication visibility.",
    focus: [
      "Consent-based parent or guardian access",
      "Attendance and academic-progress updates",
      "Fee statements, receipts and due reminders",
      "Institutional messages and support contact",
    ],
  },
  {
    href: "/platform/student-services",
    title: "Student Services",
    kind: "platform",
    summary: "Organise student-facing services through discoverable requests, appointments, cases and service-level ownership.",
    focus: [
      "Service catalogue and eligibility guidance",
      "Requests, cases and supporting documents",
      "Appointments, queues and responsible teams",
      "Service levels, feedback and completion tracking",
    ],
  },
  {
    href: "/platform/analytics",
    title: "Institutional Analytics",
    kind: "platform",
    summary: "Turn governed institutional data into role-aware dashboards, reports and decision-ready operational insight.",
    focus: [
      "Governed measures and shared data definitions",
      "Role-aware dashboards and drill-down analysis",
      "Scheduled, exportable and reviewable reports",
      "Data quality, access and interpretation controls",
    ],
  },
  {
    href: "/platform/student-success",
    title: "Student Success",
    kind: "platform",
    summary: "Coordinate explainable student-support signals, cases, interventions and outcomes without losing human accountability.",
    focus: [
      "Risk and support indicators with clear context",
      "Student-success cases and assigned ownership",
      "Intervention plans, follow-up and communication",
      "Outcome review, consent and evidence history",
    ],
  },
  {
    href: "/platform/ai",
    title: "AI Assistant",
    kind: "platform",
    summary: "Use governed AI assistance for search, drafting and workflow guidance while keeping institutional context and human review visible.",
    focus: [
      "Permission-aware information retrieval",
      "Guided task and workflow assistance",
      "Drafting support for authorised institutional work",
      "Human review, feedback and auditability",
    ],
  },
  {
    href: "/platform/workflow-automation",
    title: "Workflow Automation",
    kind: "platform",
    summary: "Configure repeatable institutional processes with triggers, approvals, handoffs, notifications and reviewable history.",
    focus: [
      "Trigger and rule configuration",
      "Approvals, routing and cross-team handoffs",
      "Notifications, reminders and escalations",
      "Workflow versioning, monitoring and audit history",
    ],
  },
  {
    href: "/platform/integrations",
    title: "Integrations",
    kind: "platform",
    summary: "Connect approved institutional systems through controlled interfaces, data mapping, monitoring and accountable ownership.",
    focus: [
      "APIs, webhooks and scheduled data exchange",
      "Identity, payment, learning and service integrations",
      "Data mapping, reconciliation and error handling",
      "Security boundaries, monitoring and support ownership",
    ],
  },
  {
    href: "/platform/multi-campus",
    title: "Multi-Campus Management",
    kind: "platform",
    summary: "Operate shared institutional services across campuses while preserving local structures, permissions and reporting context.",
    focus: [
      "Institution, campus and unit hierarchy",
      "Shared standards with local configuration",
      "Cross-campus reporting and consolidated oversight",
      "Transfers, shared services and campus-level accountability",
    ],
  },
] as const;
