import type { PublicPageSeed } from './types';

export const resourceSeeds: readonly PublicPageSeed[] = [
  {
    href: "/resources/guides",
    title: "Guides",
    kind: "resource",
    summary: "Browse practical, decision-focused guidance for evaluating, implementing and operating connected higher-education systems.",
    focus: [
      "Platform and module evaluation frameworks",
      "Implementation and migration planning",
      "Academic and administrative operating practices",
      "Security, governance and institutional readiness",
    ],
  },
  {
    href: "/resources/blog",
    title: "Blog",
    kind: "resource",
    summary: "Read product, higher-education and operational perspectives written for institutional teams.",
    focus: [
      "Product and platform updates",
      "Higher-education operations",
      "Digital transformation practices",
      "Customer and implementation perspectives",
    ],
  },
  {
    href: "/resources/research",
    title: "Research",
    kind: "resource",
    summary: "Review structured research notes and evidence-oriented perspectives relevant to institutional technology decisions.",
    focus: [
      "Higher-education technology trends",
      "Institutional operations and service design",
      "Student success and academic effectiveness",
      "Data, governance and responsible innovation",
    ],
  },
  {
    href: "/resources/webinars",
    title: "Webinars",
    kind: "resource",
    summary: "Join focused sessions with product and institutional specialists on implementation, operations and platform strategy.",
    focus: [
      "Live expert presentations",
      "Product and workflow demonstrations",
      "Institutional case discussions",
      "Question-and-answer sessions",
    ],
  },
  {
    href: "/resources/events",
    title: "Events",
    kind: "resource",
    summary: "Find CampusOS events, institutional roundtables and opportunities to discuss higher-education operations.",
    focus: [
      "Conferences and industry events",
      "Regional institutional roundtables",
      "Product briefings and workshops",
      "Community and partner sessions",
    ],
  },
  {
    href: "/resources/product-tours",
    title: "Product Tours",
    kind: "resource",
    summary: "Explore guided, fictional walkthroughs of CampusOS workspaces, modules and connected workflows.",
    focus: [
      "Role-based workspace tours",
      "Module capability walkthroughs",
      "Connected workflow demonstrations",
      "Security and governance context",
    ],
  },
  {
    href: "/careers",
    title: "Careers at CampusOS",
    kind: "resource",
    summary: "Explore opportunities to build responsible technology for higher-education institutions.",
    focus: [
      "Open roles and teams",
      "CampusOS mission and values",
      "Hiring process and candidate guidance",
      "Work environment and growth",
    ],
  },
  {
    href: "/resources/buyers-guide",
    title: "Buyer’s Guide",
    kind: "resource",
    summary: "Use a structured guide to compare institutional platforms, operating fit and implementation requirements.",
    focus: [
      "Institutional requirements definition",
      "Platform and module comparison",
      "Security and integration questions",
      "Commercial and implementation evaluation",
    ],
  },
  {
    href: "/resources/erp-evaluation-checklist",
    title: "ERP Evaluation Checklist",
    kind: "resource",
    summary: "Review a practical checklist for assessing higher-education ERP scope, usability, governance and delivery risk.",
    focus: [
      "Functional and workflow coverage",
      "Architecture, security and data controls",
      "User experience and accessibility",
      "Implementation, support and total cost",
    ],
  },
  {
    href: "/resources/rfp-toolkit",
    title: "RFP Toolkit",
    kind: "resource",
    summary: "Prepare a clearer institutional RFP with scope, evaluation criteria and evidence requests aligned to real operations.",
    focus: [
      "Requirements and use-case templates",
      "Security and technical evidence requests",
      "Implementation and support questions",
      "Evaluation scorecards and governance",
    ],
  },
  {
    href: "/resources/roi-calculator",
    title: "ROI Calculator",
    kind: "resource",
    summary: "Model potential operational impact using transparent assumptions about effort, volume, cost and adoption.",
    focus: [
      "Current-process effort baseline",
      "Implementation and subscription assumptions",
      "Efficiency and service-impact scenarios",
      "Sensitivity, payback and review notes",
    ],
  },
  {
    href: "/resources/implementation-guide",
    title: "Implementation Guide",
    kind: "resource",
    summary: "Plan discovery, configuration, migration, validation, training and controlled go-live activities.",
    focus: [
      "Scope, governance and discovery",
      "Configuration and integration planning",
      "Migration, testing and reconciliation",
      "Training, rollout and adoption",
    ],
  },
  {
    href: "/resources/data-migration-guide",
    title: "Data Migration Guide",
    kind: "resource",
    summary: "Prepare institutional data for controlled migration through inventory, mapping, cleaning, validation and reconciliation.",
    focus: [
      "Source-system and data inventory",
      "Mapping, transformation and quality rules",
      "Trial migration and exception handling",
      "Reconciliation, approval and cutover",
    ],
  },
  {
    href: "/resources/help",
    title: "Help Centre",
    kind: "resource",
    summary: "Find task-focused help for authorised CampusOS users and institutional administrators.",
    focus: [
      "Getting started and common tasks",
      "Role and module guidance",
      "Troubleshooting and support paths",
      "Administration and configuration help",
    ],
  },
  {
    href: "/developers",
    title: "Documentation",
    kind: "resource",
    summary: "Review technical documentation for approved CampusOS integrations and implementation planning.",
    focus: [
      "API and authentication concepts",
      "Data models and integration patterns",
      "Webhooks, errors and monitoring",
      "Security, environments and change management",
    ],
  },
  {
    href: "/blueprint",
    title: "Blueprint Architecture",
    kind: "resource",
    summary: "Review the CampusOS product blueprint, shared platform foundations and connected institutional architecture.",
    focus: [
      "Shared identity and tenant context",
      "Core records and modular services",
      "Workflow, integration and intelligence layers",
      "Security, observability and delivery boundaries",
    ],
  },
  {
    href: "/resources/release-notes",
    title: "Release Notes",
    kind: "resource",
    summary: "Track published product changes with clear scope, availability and action notes.",
    focus: [
      "New capabilities and improvements",
      "Resolved issues and behaviour changes",
      "Availability and rollout status",
      "Administrator and user actions",
    ],
  },
  {
    href: "/resources/roadmap",
    title: "Roadmap",
    kind: "resource",
    summary: "Review directional product priorities with appropriate status, scope and planning caveats.",
    focus: [
      "Current investment themes",
      "Planned product areas",
      "Research and discovery topics",
      "Status and availability caveats",
    ],
  },
  {
    href: "/trust/availability",
    title: "System Status",
    kind: "resource",
    summary: "Review public availability, incident and maintenance information for CampusOS services.",
    focus: [
      "Current service status",
      "Incident communication",
      "Planned maintenance",
      "Historical availability information",
    ],
  },
] as const;
