import type { PublicPageSeed } from './types';

export const roleSeeds: readonly PublicPageSeed[] = [
  {
    href: "/roles/president",
    title: "President / Vice Chancellor",
    kind: "role",
    summary: "Provide institution-wide visibility into strategic priorities, academic performance, financial health and accountable follow-up.",
    focus: [
      "Institutional strategy and performance signals",
      "Governance decisions and executive approvals",
      "Cross-campus priorities and risk visibility",
      "Accountable owners, deadlines and progress",
    ],
  },
  {
    href: "/roles/provost",
    title: "Provost / Pro Vice Chancellor",
    kind: "role",
    summary: "Coordinate academic quality, faculty capacity, programme performance and institution-wide academic priorities.",
    focus: [
      "Academic portfolio and programme performance",
      "Faculty workload and teaching capacity",
      "Quality, assessment and student-success priorities",
      "Academic approvals and cross-school coordination",
    ],
  },
  {
    href: "/roles/cio",
    title: "CIO",
    kind: "role",
    summary: "Govern institutional technology, security, integrations and service reliability through one accountable operating view.",
    focus: [
      "Application and integration portfolio",
      "Identity, access and security posture",
      "Service reliability and incident oversight",
      "Architecture, vendor and implementation decisions",
    ],
  },
  {
    href: "/roles/cfo",
    title: "CFO",
    kind: "role",
    summary: "Review revenue, collections, receivables, concessions and financial operations with clear institutional context.",
    focus: [
      "Fee revenue and collection performance",
      "Receivables, refunds and concessions",
      "Budget, cost and cash-flow visibility",
      "Financial controls, reconciliation and approvals",
    ],
  },
  {
    href: "/roles/registrar",
    title: "Registrar",
    kind: "role",
    summary: "Manage authoritative academic records, enrolment, regulations, certifications and record-governance workflows.",
    focus: [
      "Student records and enrolment status",
      "Academic regulations and progression rules",
      "Transcripts, certificates and record requests",
      "Data quality, approvals and statutory reporting",
    ],
  },
  {
    href: "/roles/dean",
    title: "Dean",
    kind: "role",
    summary: "Coordinate faculty-level programmes, teaching quality, resources and student outcomes across departments.",
    focus: [
      "Programme and curriculum performance",
      "Department capacity and faculty workload",
      "Assessment, quality and student outcomes",
      "Faculty-level approvals and resource priorities",
    ],
  },
  {
    href: "/roles/hod",
    title: "HOD / Department Chair",
    kind: "role",
    summary: "Run department teaching, staffing, schedules, assessments and student-support actions from one operational workspace.",
    focus: [
      "Teaching allocation and timetable readiness",
      "Course delivery and assessment progress",
      "Faculty workload and department actions",
      "Student risks, advising and escalations",
    ],
  },
  {
    href: "/roles/examination-controller",
    title: "Examination Controller",
    kind: "role",
    summary: "Coordinate examination planning, secure evaluation, moderation and approved result publication.",
    focus: [
      "Exam calendar, centres and candidate readiness",
      "Question-paper and evaluation controls",
      "Moderation, approval and result processing",
      "Revaluation, grievances and publication status",
    ],
  },
  {
    href: "/roles/faculty",
    title: "Faculty",
    kind: "role",
    summary: "Bring classes, attendance, assessments, advisees and assigned academic actions into one focused daily workspace.",
    focus: [
      "Teaching schedule and course responsibilities",
      "Attendance and classroom actions",
      "Assessment, grading and feedback",
      "Advising, student support and follow-up",
    ],
  },
  {
    href: "/roles/academic-advisor",
    title: "Academic Advisor",
    kind: "role",
    summary: "Support students through explainable progress signals, plans, cases and coordinated follow-up.",
    focus: [
      "Advisee progress and academic standing",
      "Attendance, performance and support indicators",
      "Intervention plans and referrals",
      "Appointments, notes and follow-up outcomes",
    ],
  },
  {
    href: "/roles/admissions",
    title: "Admissions",
    kind: "role",
    summary: "Manage applicant pipelines, documents, reviews, decisions and enrolment handoffs with clear ownership.",
    focus: [
      "Enquiry and application pipeline",
      "Document and eligibility review",
      "Selection, offers and applicant communication",
      "Enrollment activation and downstream coordination",
    ],
  },
  {
    href: "/roles/finance",
    title: "Finance",
    kind: "role",
    summary: "Run billing, collections, reconciliation, concessions and refunds through controlled financial workflows.",
    focus: [
      "Fee setup, invoicing and due schedules",
      "Payment capture and reconciliation",
      "Concession, scholarship and approval workflows",
      "Refunds, receivables and reporting",
    ],
  },
  {
    href: "/roles/hr",
    title: "HR",
    kind: "role",
    summary: "Coordinate employee records, attendance, leave, payroll inputs, performance and workforce reporting.",
    focus: [
      "Employee lifecycle and appointment records",
      "Attendance, leave and duty management",
      "Payroll inputs and benefit coordination",
      "Performance, documents and workforce analytics",
    ],
  },
  {
    href: "/roles/campus-operations",
    title: "Campus Operations",
    kind: "role",
    summary: "Manage facilities and campus services through requests, allocations, schedules and service-level accountability.",
    focus: [
      "Facilities, assets and maintenance",
      "Hostel, transport and campus services",
      "Visitor, safety and access workflows",
      "Helpdesk queues, service levels and reporting",
    ],
  },
  {
    href: "/roles/student-success",
    title: "Student Success",
    kind: "role",
    summary: "Coordinate student-support cases, interventions and outcomes across advisors, faculty and service teams.",
    focus: [
      "Explainable support and risk indicators",
      "Case assignment and intervention planning",
      "Cross-team referrals and communication",
      "Outcome tracking and programme improvement",
    ],
  },
  {
    href: "/roles/career-services",
    title: "Career Services",
    kind: "role",
    summary: "Connect students, employers, opportunities and placement processes through structured career-service workflows.",
    focus: [
      "Student profiles and career readiness",
      "Employer, job and internship relationships",
      "Application, interview and offer tracking",
      "Placement outcomes and programme reporting",
    ],
  },
  {
    href: "/roles/student",
    title: "Student",
    kind: "role",
    summary: "Give students a clear view of learning, attendance, assessments, fees, documents and campus services.",
    focus: [
      "Classes, timetable and learning access",
      "Attendance, assignments and results",
      "Fees, receipts and documents",
      "Requests, notifications and support services",
    ],
  },
  {
    href: "/roles/parent",
    title: "Parent or Guardian",
    kind: "role",
    summary: "Provide authorised, consent-aware visibility into attendance, academic progress, fees and institutional communication.",
    focus: [
      "Permission and consent-based access",
      "Attendance and academic updates",
      "Fee statements and due information",
      "Messages, alerts and support contact",
    ],
  },
  {
    href: "/roles/alumni",
    title: "Alumni",
    kind: "role",
    summary: "Support ongoing alumni engagement, records, events, opportunities and institutional relationships.",
    focus: [
      "Alumni profile and contact preferences",
      "Events, communities and communication",
      "Career, mentoring and giving opportunities",
      "Verification requests and engagement insight",
    ],
  },
] as const;
