import type { PublicPageSeed } from './types';

export const securitySeeds: readonly PublicPageSeed[] = [
  {
    href: "/security",
    title: "Security Overview",
    kind: "security",
    summary: "Review the CampusOS security approach across identity, access, data protection, monitoring and accountable operations.",
    focus: [
      "Security architecture and responsibility model",
      "Identity, authorization and tenant context",
      "Data, file and integration protection",
      "Monitoring, review and incident practices",
    ],
  },
  {
    href: "/trust",
    title: "Trust Centre",
    kind: "security",
    summary: "Access public security, privacy, availability and procurement information for institutional evaluation.",
    focus: [
      "Security and control information",
      "Privacy and data-handling information",
      "Availability and continuity information",
      "Procurement and assurance resources",
    ],
  },
  {
    href: "/trust/privacy",
    title: "Privacy",
    kind: "security",
    summary: "Review how privacy responsibilities, authorised access and institutional configuration are considered in CampusOS operations.",
    focus: [
      "Purpose and data-role clarity",
      "Access, consent and institutional responsibility",
      "Retention, requests and data lifecycle",
      "Transparency, subprocessors and contact paths",
    ],
  },
  {
    href: "/trust/data-portability",
    title: "Data Portability and Plan Exit",
    kind: "security",
    summary: "Understand planning considerations for exports, transition support and institution-controlled exit activities.",
    focus: [
      "Export scope and supported formats",
      "Identity, records and document handoff",
      "Transition planning and validation",
      "Retention, deletion and responsibility boundaries",
    ],
  },
  {
    href: "/security/accessibility",
    title: "Accessibility",
    kind: "security",
    summary: "Review design and delivery practices intended to support accessible CampusOS experiences.",
    focus: [
      "Keyboard and assistive-technology support",
      "Readable structure, contrast and focus",
      "Responsive and adaptable interfaces",
      "Testing, feedback and remediation",
    ],
  },
  {
    href: "/trust/subprocessors",
    title: "Subprocessors",
    kind: "security",
    summary: "Review published information about service providers that may support CampusOS delivery.",
    focus: [
      "Provider purpose and service category",
      "Data-processing context",
      "Change communication",
      "Institutional review and contact paths",
    ],
  },
  {
    href: "/security/vulnerability-disclosure",
    title: "Vulnerability Disclosure",
    kind: "security",
    summary: "Report potential security issues responsibly through a clear intake and coordination process.",
    focus: [
      "Safe reporting channels",
      "Required technical details",
      "Triage and communication process",
      "Disclosure boundaries and researcher guidance",
    ],
  },
  {
    href: "/security/identity-access",
    title: "Identity and Access",
    kind: "security",
    summary: "Apply institution-configured identity, authentication and permission controls to CampusOS users and workflows.",
    focus: [
      "Authentication and account lifecycle",
      "Role and attribute-based authorization",
      "Tenant, campus and institutional context",
      "Privileged access and periodic review",
    ],
  },
  {
    href: "/security/data-protection",
    title: "Data Protection",
    kind: "security",
    summary: "Protect sensitive institutional information through controlled storage, transmission, access and lifecycle practices.",
    focus: [
      "Encryption and secure transport",
      "Private storage and file access",
      "Data classification and minimisation",
      "Backup, retention and disposal planning",
    ],
  },
  {
    href: "/security/audit-monitoring",
    title: "Audit and Monitoring",
    kind: "security",
    summary: "Maintain reviewable activity context and operational monitoring for important CampusOS actions and services.",
    focus: [
      "Actor, time, action and record history",
      "Security and service monitoring",
      "Alerting, investigation and escalation",
      "Retention, review and evidence handling",
    ],
  },
  {
    href: "/security/payment-security",
    title: "Payment Security",
    kind: "security",
    summary: "Plan secure fee-payment workflows with controlled integrations, reconciliation and limited exposure of payment data.",
    focus: [
      "Payment-provider integration boundaries",
      "Transaction status and reconciliation",
      "Access control and fraud-aware review",
      "Receipts, refunds and exception handling",
    ],
  },
  {
    href: "/security/biometric-security",
    title: "Biometric Security",
    kind: "security",
    summary: "Review safeguards for institution-configured biometric features, including consent, storage and limited use.",
    focus: [
      "Purpose limitation and informed consent",
      "Template protection and restricted access",
      "Fallback and exception workflows",
      "Retention, deletion and auditability",
    ],
  },
  {
    href: "/security/ai-governance",
    title: "AI Governance",
    kind: "security",
    summary: "Apply responsible AI controls to permission-aware assistance, human review, monitoring and institutional policy.",
    focus: [
      "Approved use cases and data boundaries",
      "Human review and accountability",
      "Output quality, feedback and monitoring",
      "Change control, transparency and audit history",
    ],
  },
] as const;
