import type { PublicPageSeed } from './types';

export const solutionSeeds: readonly PublicPageSeed[] = [
  {
    href: "/solutions/public-universities",
    title: "Public Universities",
    kind: "solution",
    summary: "Coordinate complex academic structures, public accountability and institution-wide services across large student populations.",
    focus: [
      "Multi-faculty academic governance",
      "High-volume student and administrative services",
      "Public reporting and accountable approvals",
      "Campus, department and programme coordination",
    ],
  },
  {
    href: "/solutions/private-universities",
    title: "Private Universities",
    kind: "solution",
    summary: "Connect academic delivery, student experience, finance and growth operations within a configurable university model.",
    focus: [
      "Programme launch and academic agility",
      "Admissions, fees and student-service coordination",
      "Institution-wide performance visibility",
      "Multi-campus growth and operating consistency",
    ],
  },
  {
    href: "/solutions/community-colleges",
    title: "Community Colleges",
    kind: "solution",
    summary: "Support accessible enrolment, flexible programmes and student-support workflows for diverse learner pathways.",
    focus: [
      "Open and flexible enrolment models",
      "Transfer, certificate and workforce programmes",
      "Advising and student-support coordination",
      "Part-time, adult and returning learner services",
    ],
  },
  {
    href: "/solutions/liberal-arts-colleges",
    title: "Liberal Arts Colleges",
    kind: "solution",
    summary: "Support interdisciplinary learning, close faculty engagement and personalised student services in a residential or community-focused model.",
    focus: [
      "Interdisciplinary curriculum and advising",
      "Small-cohort teaching and faculty engagement",
      "Residential and co-curricular experience",
      "Personalised academic and student support",
    ],
  },
  {
    href: "/solutions/research-universities",
    title: "Research Universities",
    kind: "solution",
    summary: "Coordinate complex academic, research and administrative structures without flattening institutional responsibilities.",
    focus: [
      "Graduate and undergraduate academic structures",
      "Research administration and faculty workload context",
      "Cross-school governance and reporting",
      "Complex identity, access and data boundaries",
    ],
  },
  {
    href: "/solutions/online-and-hybrid-learning",
    title: "Online and Hybrid Institutions",
    kind: "solution",
    summary: "Deliver flexible digital learning with remote engagement, scalable services and clear academic accountability.",
    focus: [
      "Online programme and cohort operations",
      "Digital course delivery and live learning",
      "Remote assessment and identity controls",
      "Learner engagement and support visibility",
    ],
  },
  {
    href: "/solutions/central-state-universities",
    title: "Central and State Universities",
    kind: "solution",
    summary: "Support distributed faculties, affiliated structures and public-sector governance with clear institutional context.",
    focus: [
      "Faculty, department and campus hierarchy",
      "Academic regulation and examination coordination",
      "Government and statutory reporting readiness",
      "Shared services with local responsibility",
    ],
  },
  {
    href: "/solutions/autonomous-colleges",
    title: "Autonomous Colleges",
    kind: "solution",
    summary: "Manage independent curricula, examination rules and academic-quality processes with reviewable institutional governance.",
    focus: [
      "Curriculum autonomy and regulation versioning",
      "Examination, moderation and result workflows",
      "Outcome-based education and evidence management",
      "Academic council approvals and reporting",
    ],
  },
  {
    href: "/solutions/affiliated-colleges",
    title: "Affiliated Colleges",
    kind: "solution",
    summary: "Coordinate college operations while aligning records, examinations and reporting with affiliating-university requirements.",
    focus: [
      "Affiliation and programme-rule alignment",
      "Student, examination and result submissions",
      "Local academic delivery and attendance",
      "Evidence, deadlines and compliance coordination",
    ],
  },
  {
    href: "/solutions/engineering-colleges",
    title: "Engineering Colleges",
    kind: "solution",
    summary: "Support laboratories, projects, technical programmes, placements and outcome-based academic operations.",
    focus: [
      "Laboratory, workshop and equipment planning",
      "Projects, internships and technical assessments",
      "Programme outcomes and accreditation evidence",
      "Placement and industry-engagement workflows",
    ],
  },
  {
    href: "/solutions/medical-institutions",
    title: "Medical Institutions",
    kind: "solution",
    summary: "Coordinate academic schedules, clinical rotations, duty rosters and specialised attendance requirements.",
    focus: [
      "Clinical rotations and posting schedules",
      "Duty rosters and attendance by activity",
      "Competency, assessment and logbook workflows",
      "Hospital, department and academic coordination",
    ],
  },
  {
    href: "/solutions/college-groups",
    title: "Multi-College Groups",
    kind: "solution",
    summary: "Operate multiple institutions through shared governance, central services and configurable local control.",
    focus: [
      "Group, institution and campus hierarchy",
      "Central finance, HR and procurement services",
      "Local academic and operational configuration",
      "Consolidated reporting with institutional drill-down",
    ],
  },
  {
    href: "/solutions/legacy-system-replacement",
    title: "Legacy ERP Replacement",
    kind: "solution",
    summary: "Replace fragmented or ageing systems through phased discovery, migration, validation and controlled adoption.",
    focus: [
      "Current-system and dependency assessment",
      "Data migration and reconciliation planning",
      "Priority workflow redesign and integration transition",
      "Phased rollout, coexistence and retirement controls",
    ],
  },
  {
    href: "/solutions/enrollment-modernization",
    title: "Enrollment Modernization",
    kind: "solution",
    summary: "Create a connected applicant journey from enquiry through decision, payment and active enrolment.",
    focus: [
      "Digital enquiry and application experience",
      "Document, eligibility and review workflow",
      "Selection, offer and seat-allocation process",
      "Enrollment handoff to records, finance and academics",
    ],
  },
  {
    href: "/solutions/student-retention",
    title: "Student Retention",
    kind: "solution",
    summary: "Bring explainable signals, assigned cases and coordinated interventions into a governed student-success process.",
    focus: [
      "Attendance, progress and engagement signals",
      "Case ownership and intervention planning",
      "Advisor, faculty and service-team coordination",
      "Outcome review and support-programme improvement",
    ],
  },
  {
    href: "/solutions/multi-campus",
    title: "Multi-Campus Operations",
    kind: "solution",
    summary: "Standardise shared operations across campuses while preserving local structures, permissions and service accountability.",
    focus: [
      "Shared policies with campus-level configuration",
      "Cross-campus services and resource planning",
      "Local queues, approvals and escalation paths",
      "Consolidated reporting and comparison",
    ],
  },
  {
    href: "/solutions/academic-automation",
    title: "Academic Automation",
    kind: "solution",
    summary: "Reduce repetitive academic administration through controlled rules, approvals, notifications and exception handling.",
    focus: [
      "Academic calendar and scheduling automation",
      "Enrollment, attendance and assessment rules",
      "Approval routing and deadline reminders",
      "Exception queues and reviewable workflow history",
    ],
  },
  {
    href: "/solutions/compliance-readiness",
    title: "Compliance Readiness",
    kind: "solution",
    summary: "Organise responsibilities, evidence and review cycles that support institution-led regulatory and accreditation preparation.",
    focus: [
      "Control ownership and evidence registers",
      "Policy, review and approval schedules",
      "Issue, action and remediation tracking",
      "Reporting packs and audit-ready history",
    ],
  },
] as const;
