import Link from 'next/link';
import { notFound } from 'next/navigation';
import { titleFromSlug, regions, type Region } from './site-data';

const sections: Record<string, { eyebrow: string; intro: string; modules: string[] }> = {
  platform: { eyebrow: 'CONNECTED PLATFORM', intro: 'CampusOS brings the work of academic, administrative, and student-facing teams into a governed operating model.', modules: ['Connected records','Configurable workflows','Institutional reporting'] },
  solutions: { eyebrow: 'INSTITUTIONAL SOLUTIONS', intro: 'Purpose-built operating patterns for the priorities, governance, and service models of higher education.', modules: ['Institution-aware configuration','Cross-team visibility','Phased implementation'] },
  roles: { eyebrow: 'ROLE-BASED OPERATIONS', intro: 'Give every university role the right workspaces, alerts, and evidence—without broadening access to sensitive data.', modules: ['Prioritized work','Role-specific reporting','Responsible access'] },
  security: { eyebrow: 'TRUST AND SECURITY', intro: 'Controls and operating practices designed to support institution-configured privacy, security, and readiness programmes.', modules: ['Identity controls','Accountable monitoring','Documented review'] },
  pricing: { eyebrow: 'FLEXIBLE PROCUREMENT', intro: 'Shape CampusOS around your institution’s modules, campuses, student population, and implementation approach.', modules: ['Annual agreements','Implementation planning','Procurement support'] },
  resources: { eyebrow: 'CAMPUSOS RESOURCES', intro: 'Original, practical material for teams selecting, implementing, and operating connected higher-education systems.', modules: ['Decision support','Implementation guidance','Operational playbooks'] },
  legal: { eyebrow: 'LEGAL AND DATA INFORMATION', intro: 'Review the public information that supports transparent, responsible CampusOS operations and procurement conversations.', modules: ['Clear information','Reviewable practices','Institutional context'] },
  about: { eyebrow: 'ABOUT CAMPUSOS', intro: 'CampusOS helps higher-education institutions coordinate the work that enables learning, service, and accountable administration.', modules: ['Higher-education focus','Connected operations','Responsible delivery'] },
  contact: { eyebrow: 'CONTACT CAMPUSOS', intro: 'Connect with a CampusOS specialist to discuss your institution’s operating priorities and implementation needs.', modules: ['Discovery conversation','Regional context','Implementation planning'] },
  demo: { eyebrow: 'CAMPUSOS DEMO', intro: 'See a focused walkthrough of the workspaces and workflows most relevant to your institution.', modules: ['Role-based walkthrough','Workflow discussion','Next-step plan'] },
  integrations: { eyebrow: 'INTEGRATIONS', intro: 'Plan a connected higher-education technology environment with deliberate data, ownership, and operating boundaries.', modules: ['Integration planning','Data ownership','Migration readiness'] },
  trust: { eyebrow: 'CAMPUSOS TRUST CENTRE', intro: 'Public information about CampusOS security, privacy, availability, and continuity practices.', modules: ['Security overview','Privacy information','Availability planning'] },
  developers: { eyebrow: 'DEVELOPER PORTAL', intro: 'Technical resources for teams planning controlled, accountable CampusOS integrations.', modules: ['API planning','Integration patterns','Technical support'] },
  partners: { eyebrow: 'CAMPUSOS PARTNERS', intro: 'Work with CampusOS to support thoughtful higher-education transformation and adoption.', modules: ['Delivery partners','Technology partners','Shared outcomes'] },
  status: { eyebrow: 'SYSTEM STATUS', intro: 'View current public service status and planned operational communications.', modules: ['Service visibility','Incident communication','Maintenance planning'] },
};

export function PublicPage({ segments, region = 'us' }: { segments: string[]; region?: Region }) {
  const root = segments[0]; const config = sections[root]; if (!config) notFound();
  const title = segments.length === 1 ? titleFromSlug(root) : titleFromSlug(segments[segments.length - 1]);
  const local = regions[region];
  const isSecurity = root === 'security' || segments[0] === 'trust';
  return <div className="bg-white text-slate-900">
    <section className="border-b border-slate-200 bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:py-20"><nav aria-label="Breadcrumb" className="mb-7 text-sm text-slate-600"><Link href="/" className="hover:text-blue-800">Home</Link><span className="px-2">/</span><Link href={`/${root}`} className="hover:text-blue-800">{titleFromSlug(root)}</Link>{segments.length > 1 && <><span className="px-2">/</span><span>{title}</span></>}</nav><p className="text-xs font-bold tracking-[.16em] text-blue-800">{config.eyebrow}</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">{title} for modern higher education</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">{config.intro} Built for a {local.institution}, with terminology and implementation conversations appropriate for {local.label}.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="min-h-11 rounded-md bg-blue-700 px-5 py-3 text-sm font-semibold text-white hover:bg-blue-800" href="/demo">Book a demo</Link><Link className="min-h-11 rounded-md border border-slate-300 px-5 py-3 text-sm font-semibold text-slate-800 hover:bg-white" href="/resources/guides">Explore guides</Link></div></div></section>
    <main id="main-content"><section className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[1fr_.85fr] lg:py-20"><div><h2 className="text-3xl font-semibold">Designed around accountable work</h2><p className="mt-4 leading-7 text-slate-600">Replace disconnected handoffs with visible ownership, clear approvals, and context that follows the learner or institutional process. Teams can configure workflows to their policies and retain evidence for review.</p><dl className="mt-8 grid gap-4 sm:grid-cols-3">{config.modules.map((m, i) => <div key={m} className="rounded-lg border border-slate-200 p-4"><dt className="text-sm font-semibold text-slate-900">0{i + 1}</dt><dd className="mt-2 text-sm text-slate-600">{m}</dd></div>)}</dl></div><ProductPreview title={title} /></section>
    <section className="bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:py-20"><h2 className="text-3xl font-semibold">From daily work to institutional insight</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{['Coordinate', 'Measure', 'Improve'].map((step, i) => <article key={step} className="rounded-lg border border-slate-200 bg-white p-6"><p className="text-sm font-bold text-blue-800">0{i + 1}</p><h3 className="mt-5 text-lg font-semibold">{step} with context</h3><p className="mt-2 text-sm leading-6 text-slate-600">Give teams a consistent path for decisions, exceptions, and follow-up while keeping the responsible role in control.</p></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:py-20"><div className="grid gap-10 md:grid-cols-2"><div><h2 className="text-3xl font-semibold">Implementation and integration</h2><p className="mt-4 leading-7 text-slate-600">Start with the workflows that matter most, then connect supported systems through planned data migration and integration work. CampusOS implementation teams align scope, roles, governance, and adoption milestones with your institution.</p></div><div className="rounded-lg border border-slate-200 p-6"><h3 className="font-semibold">Security consideration</h3><p className="mt-3 text-sm leading-6 text-slate-600">Access is designed around institution-configured roles and reviewable actions. {isSecurity ? 'This page describes product practices, not a certification or legal conclusion.' : 'Review security and privacy requirements with your institution during implementation.'}</p><Link href="/security" className="mt-4 inline-block text-sm font-semibold text-blue-800 hover:underline">Review trust information</Link></div></div></section>
    <section className="border-y border-slate-200 bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8"><h2 className="text-3xl font-semibold">Frequently asked questions</h2><div className="mt-6 divide-y divide-slate-200 rounded-lg border border-slate-200 bg-white">{['Can CampusOS work with our current systems?', 'How is rollout planned?', 'How do regional needs affect configuration?'].map(q => <details key={q} className="group p-5"><summary className="cursor-pointer font-semibold marker:text-blue-700">{q}</summary><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">CampusOS is configured with your institutional teams. We scope integrations, migration, governance, and regional terminology during discovery; your institution retains responsibility for policy and regulatory decisions.</p></details>)}</div></div></section>
    <section className="bg-slate-900"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 px-5 py-14 sm:px-8 md:flex-row md:items-center"><div><h2 className="text-3xl font-semibold text-white">Plan the next stage of your campus operations.</h2><p className="mt-2 text-slate-300">Talk with a CampusOS specialist for {local.label}.</p></div><Link href="/demo" className="min-h-11 rounded-md bg-white px-5 py-3 text-sm font-semibold text-slate-900 hover:bg-slate-100">Book a demo</Link></div></section></main></div>;
}

function ProductPreview({ title }: { title: string }) { return <div className="rounded-xl border border-slate-300 bg-slate-900 p-3 shadow-sm"><div className="rounded-lg bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-slate-500">CAMPUSOS WORKSPACE</p><p className="mt-1 font-semibold">{title}</p></div><span className="rounded-full bg-emerald-100 px-2 py-1 text-xs font-medium text-emerald-800">In review</span></div><div className="mt-6 grid grid-cols-3 gap-3">{['Priority tasks','Approvals','Reports'].map((x,i) => <div key={x} className="rounded-md border border-slate-200 p-3"><div className="h-1.5 w-8 rounded bg-blue-700"/><p className="mt-4 text-xs font-medium text-slate-700">{x}</p><p className="mt-1 text-lg font-semibold">{[12,4,8][i]}</p></div>)}</div><div className="mt-4 h-24 rounded-md border border-slate-200 bg-slate-50 p-4"><div className="h-2 w-3/4 rounded bg-slate-300"/><div className="mt-3 h-2 w-full rounded bg-slate-200"/><div className="mt-3 h-2 w-2/3 rounded bg-slate-200"/></div></div></div>; }
