'use client';

import { Check, ChevronDown, Globe2, X } from 'lucide-react';
import { useEffect, useId, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { regions, type Region } from './site-data';

type RegionOption = { code: Region; label: string; description: string; flag: 'globe' | 'us' | 'in' };
const options: RegionOption[] = [
  { code: 'global', label: 'Global', description: 'International product information', flag: 'globe' },
  { code: 'us', label: 'United States', description: 'US terminology, solutions and resources', flag: 'us' },
  { code: 'in', label: 'India', description: 'India terminology, institutions and resources', flag: 'in' },
];

export function RegionSelector({ compact = false }: { compact?: boolean }) {
  const router = useRouter(); const id = useId(); const triggerRef = useRef<HTMLButtonElement>(null); const optionRefs = useRef<Array<HTMLButtonElement | null>>([]);
  const [region, setRegion] = useState<Region>('global'); const [open, setOpen] = useState(false); const [active, setActive] = useState(0); const [mobile, setMobile] = useState(false); const [announcement, setAnnouncement] = useState('');
  useEffect(() => { const stored = document.cookie.match(/(?:^|; )campus_region=([^;]+)/)?.[1] as Region; const current = stored && regions[stored] ? stored : 'global'; setRegion(current); setActive(Math.max(0, options.findIndex(x => x.code === current))); const media = window.matchMedia('(max-width: 767px)'); const update = () => setMobile(media.matches); update(); media.addEventListener('change', update); return () => media.removeEventListener('change', update); }, []);
  useEffect(() => { if (!open) return; const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); close(); } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [open]);
  function close(returnFocus = true) { setOpen(false); if (returnFocus) requestAnimationFrame(() => triggerRef.current?.focus()); }
  function choose(code: Region) { const choice = options.find(item => item.code === code)!; setRegion(code); setActive(options.findIndex(item => item.code === code)); document.cookie = `campus_region=${code}; path=/; max-age=31536000; SameSite=Lax`; setAnnouncement(`Region changed to ${choice.label}.`); close(); router.refresh(); }
  function triggerKeyDown(event: React.KeyboardEvent<HTMLButtonElement>) { if (['ArrowDown', 'ArrowUp', 'Enter', ' '].includes(event.key)) { event.preventDefault(); setOpen(true); const next = event.key === 'ArrowUp' ? Math.max(0, active - 1) : active; requestAnimationFrame(() => optionRefs.current[next]?.focus()); } }
  function optionKeyDown(event: React.KeyboardEvent<HTMLButtonElement>, index: number) { let next = index; if (event.key === 'ArrowDown') next = Math.min(options.length - 1, index + 1); if (event.key === 'ArrowUp') next = Math.max(0, index - 1); if (event.key === 'Home') next = 0; if (event.key === 'End') next = options.length - 1; if (next !== index) { event.preventDefault(); setActive(next); optionRefs.current[next]?.focus(); } if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); choose(options[index].code); } }
  const selected = options.find(item => item.code === region)!;
  return <div className={`relative ${compact ? '' : 'inline-block'}`}><button ref={triggerRef} type="button" aria-label={`Choose your region. Current region: ${selected.label}`} aria-haspopup="listbox" aria-expanded={open} aria-controls={`${id}-listbox`} onClick={() => setOpen(value => !value)} onKeyDown={triggerKeyDown} className="flex min-h-11 min-w-[136px] max-w-44 items-center gap-2 rounded-md border border-[#DCE4EF] bg-white px-3 text-sm font-medium text-[#172033] hover:bg-[#F7F9FC] focus:outline-none focus:ring-2 focus:ring-[#1754E8] focus:ring-offset-2"><RegionFlag flag={selected.flag}/><span className="min-w-0 flex-1 truncate text-left">{selected.label}</span><ChevronDown size={16} aria-hidden="true" className={`shrink-0 transition-transform ${open ? 'rotate-180' : ''}`}/></button><span className="sr-only" aria-live="polite">{announcement}</span>{open && <RegionSelectorPanel mobile={mobile} id={`${id}-listbox`} selected={region} active={active} onClose={() => close()} onChoose={choose} onOptionKeyDown={optionKeyDown} optionRefs={optionRefs}/>}</div>;
}

function RegionSelectorPanel({ mobile, id, selected, active, onClose, onChoose, onOptionKeyDown, optionRefs }: { mobile: boolean; id: string; selected: Region; active: number; onClose: () => void; onChoose: (region: Region) => void; onOptionKeyDown: (event: React.KeyboardEvent<HTMLButtonElement>, index: number) => void; optionRefs: React.MutableRefObject<Array<HTMLButtonElement | null>> }) {
  const content = <div className="p-2"><div className="border-b border-[#E5EAF1] px-3 pb-3 pt-2"><p className="text-sm font-semibold text-[#172033]">Choose your region</p><p className="mt-1 text-xs leading-5 text-[#667085]">Regional content changes terminology, resources and product examples.</p></div><div id={id} role="listbox" aria-label="Choose your region" className="pt-2">{options.map((option, index) => <button key={option.code} ref={node => { optionRefs.current[index] = node; }} role="option" aria-selected={selected === option.code} tabIndex={active === index ? 0 : -1} onClick={() => onChoose(option.code)} onKeyDown={event => onOptionKeyDown(event, index)} className={`flex min-h-[64px] w-full items-center gap-3 rounded-lg px-3 py-2 text-left focus:outline-none focus:ring-2 focus:ring-[#1754E8] ${selected === option.code ? 'bg-[#EEF3FF]' : 'hover:bg-[#F7F9FC]'}`}><RegionFlag flag={option.flag}/><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-[#172033]">{option.label}</span><span className="mt-0.5 block text-xs leading-4 text-[#667085]">{option.description}</span></span>{selected === option.code && <Check size={18} className="shrink-0 text-[#1754E8]" aria-label="Selected"/>}</button>)}</div></div>;
  if (mobile) return <div role="dialog" aria-modal="true" aria-label="Choose your region" className="fixed inset-0 z-[75] flex items-end bg-slate-950/30 p-0 sm:p-4"><div className="w-full rounded-t-2xl bg-white pb-[max(1rem,env(safe-area-inset-bottom))] shadow-2xl sm:mx-auto sm:max-w-md sm:rounded-2xl"><div className="flex items-center justify-between border-b border-[#E5EAF1] px-4 py-3"><span className="text-sm font-semibold text-[#172033]">Region settings</span><button type="button" onClick={onClose} className="min-h-11 min-w-11 rounded-md text-[#172033] hover:bg-[#F7F9FC]" aria-label="Close region selector"><X className="mx-auto" size={18}/></button></div>{content}</div></div>;
  return <div className="absolute right-0 top-[calc(100%+8px)] z-[65] w-[min(320px,calc(100vw-24px))] rounded-xl border border-[#DCE4EF] bg-white shadow-[0_12px_28px_rgba(16,24,40,.14)]">{content}</div>;
}

function RegionFlag({ flag }: { flag: RegionOption['flag'] }) { if (flag === 'globe') return <span className="flex h-5 w-6 items-center justify-center text-[#1754E8]" aria-hidden="true"><Globe2 size={19}/></span>; if (flag === 'us') return <svg role="img" aria-label="United States flag" viewBox="0 0 22 16" className="h-4 w-[22px] shrink-0 rounded-[3px] border border-slate-200"><rect width="22" height="16" fill="#fff"/>{[1,3,5,7,9,11,13,15].map(y => <path key={y} d={`M0 ${y}h22v1H0z`} fill="#B22234"/>)}<rect width="10" height="8" fill="#3C3B6E"/></svg>; return <svg role="img" aria-label="India flag" viewBox="0 0 22 16" className="h-4 w-[22px] shrink-0 rounded-[3px] border border-slate-200"><path d="M0 0h22v5.34H0z" fill="#FF9933"/><path d="M0 5.33h22v5.34H0z" fill="#fff"/><path d="M0 10.67h22V16H0z" fill="#138808"/><circle cx="11" cy="8" r="1.7" fill="none" stroke="#000080" strokeWidth=".55"/></svg>; }
