'use client';
import { useState } from 'react';

const content = {
  us: { label: 'United States', title: 'Designed for the operating reality of US institutions', items: ['Student information and enrollment workflows', 'Financial-aid integration planning where implemented', 'Student-success, residence-life, and campus-safety workflows', 'Accessible digital experiences and controlled record access'] },
  in: { label: 'India', title: 'Designed for the operating reality of Indian institutions', items: ['Academic ERP, examination cell, fees, and scholarship workflows', 'Hostel, transport, and multi-campus administration', 'Outcome-Based Education and accreditation-evidence workflows', 'Student grievance and institutional-readiness workflows'] },
  global: { label: 'Global', title: 'Built to adapt to your institutional model', items: ['Configurable terminology, workflows, and role boundaries', 'Planned implementation around regional operating requirements', 'Controlled access to institution-owned student and operational data', 'Localisation foundations for multi-campus institutions'] },
};

export function RegionalCapabilities() {
  const [region, setRegion] = useState<keyof typeof content>('us'); const current = content[region];
  return <section className="bg-[#F6F8FC] py-16 md:py-24"><div className="mx-auto max-w-[1440px] px-4 md:px-6 lg:px-10 xl:px-12"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="text-xs font-bold tracking-[.14em] text-[#1754E8]">REGIONALLY ADAPTABLE</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-[#101A32] md:text-4xl">One operating foundation, adapted to local needs.</h2><p className="mt-5 max-w-xl text-base leading-7 text-[#5F6C7B]">CampusOS supports institution-configured workflows and is designed to assist with readiness planning. It does not determine legal compliance for your institution.</p></div><div><div role="tablist" aria-label="Regional capabilities" className="flex gap-2 overflow-x-auto border-b border-[#DFE6F0] pb-3">{(Object.keys(content) as Array<keyof typeof content>).map(key => <button key={key} role="tab" aria-selected={region === key} onClick={() => setRegion(key)} className={`min-h-11 whitespace-nowrap rounded-md px-4 text-sm font-semibold ${region === key ? 'bg-[#1754E8] text-white' : 'bg-white text-[#5F6C7B] hover:bg-[#F0F4FA]'}`}>{content[key].label}</button>)}</div><div className="mt-5 rounded-2xl border border-[#DFE6F0] bg-white p-6 shadow-sm"><h3 className="text-xl font-semibold text-[#101828]">{current.title}</h3><ul className="mt-5 grid gap-3 sm:grid-cols-2">{current.items.map(item => <li key={item} className="flex gap-3 text-sm leading-6 text-[#5F6C7B]"><span className="mt-2 h-2 w-2 shrink-0 rounded-sm bg-[#1754E8]" aria-hidden="true"/>{item}</li>)}</ul></div></div></div></div></section>;
}
