import React from 'react';

const steps = [
  { id: '1', title: 'Admission approved', desc: 'Applicant status changes to admitted.' },
  { id: '2', title: 'Student profile created', desc: 'Core ERP record auto-generates.' },
  { id: '3', title: 'Fee invoice generated', desc: 'Semester dues applied instantly.' },
  { id: '4', title: 'Courses registered', desc: 'Academic plan assigned.' },
  { id: '5', title: 'Timetable assigned', desc: 'Batches and sections formed.' },
  { id: '6', title: 'Attendance recorded', desc: 'Faculty mark daily presence.' },
  { id: '7', title: 'Results published', desc: 'End-of-term grades released.' }
];

export function WorkflowSection() {
  return (
    <section className="bg-white py-24 md:py-32 overflow-hidden border-t border-[#DEE5EF]">
      <div className="max-w-[1440px] mx-auto px-4 md:px-6 lg:px-8 xl:px-12">
        <div className="text-center mb-16">
          <span className="text-[12px] md:text-[13px] font-semibold text-[#1854E8] tracking-[0.08em] uppercase mb-4 block">
            AUTOMATED WORKFLOWS
          </span>
          <h2 className="text-3xl md:text-4xl lg:text-[42px] font-bold text-[#101B33] mb-6">
            Data flows naturally from start to finish
          </h2>
          <p className="text-[17px] text-[#5F6B7A] max-w-[680px] mx-auto">
            When an applicant becomes a student, CampusOS automatically provisions their profile, generates invoices, and builds their academic schedule without manual data entry.
          </p>
        </div>

        {/* Desktop Horizontal Workflow */}
        <div className="hidden lg:block relative max-w-[1200px] mx-auto mb-20">
          <div className="absolute top-[28px] left-8 right-8 h-[2px] bg-[#DEE5EF] -z-10"></div>
          
          <div className="flex justify-between">
            {steps.map((step, index) => (
              <div key={index} className="flex flex-col items-center text-center w-[140px]">
                <div className="w-14 h-14 rounded-full bg-white border-2 border-[#1854E8] text-[#1854E8] flex items-center justify-center font-bold text-[18px] mb-4 shadow-[0_0_0_8px_white]">
                  {step.id}
                </div>
                <h4 className="text-[14px] font-bold text-[#101828] mb-1">{step.title}</h4>
                <p className="text-[12px] text-[#5F6B7A] leading-tight px-2">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Mobile/Tablet Vertical Workflow */}
        <div className="lg:hidden relative max-w-[400px] mx-auto mb-16 pl-6">
          <div className="absolute top-[28px] bottom-[28px] left-[34px] w-[2px] bg-[#DEE5EF] -z-10"></div>
          
          <div className="flex flex-col gap-8">
            {steps.map((step, index) => (
              <div key={index} className="flex gap-6 items-start">
                <div className="w-10 h-10 shrink-0 rounded-full bg-white border-2 border-[#1854E8] text-[#1854E8] flex items-center justify-center font-bold text-[14px] shadow-[0_0_0_8px_white]">
                  {step.id}
                </div>
                <div className="pt-2">
                  <h4 className="text-[15px] font-bold text-[#101828] mb-1">{step.title}</h4>
                  <p className="text-[13px] text-[#5F6B7A] leading-tight">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Supporting Automation Log UI */}
        <div className="max-w-[800px] mx-auto">
          <div className="bg-white rounded-xl border border-[#DEE5EF] shadow-sm overflow-hidden">
            <div className="h-12 bg-[#F5F7FB] border-b border-[#DEE5EF] px-5 flex items-center">
              <span className="text-[13px] font-semibold text-[#101828]">System Activity Log: Enrollment Automation</span>
            </div>
            <div className="p-5 flex flex-col gap-4">
              <div className="flex gap-4">
                <div className="text-[12px] font-medium text-[#5F6B7A] w-[60px] pt-0.5">09:41</div>
                <div className="flex-1">
                  <div className="text-[13px] font-semibold text-[#101828]">Admission status updated to <span className="bg-[#e6f4ed] text-[#078A57] px-1.5 py-0.5 rounded">Approved</span></div>
                  <div className="text-[12px] text-[#5F6B7A]">Triggered by Admissions Dept.</div>
                </div>
              </div>
              <div className="flex gap-4">
                <div className="text-[12px] font-medium text-[#5F6B7A] w-[60px] pt-0.5">09:41</div>
                <div className="flex-1">
                  <div className="text-[13px] font-semibold text-[#101828]">Student Profile Created (ID: STU-2024-892)</div>
                  <div className="text-[12px] text-[#5F6B7A]">Auto-generated by System</div>
                </div>
              </div>
              <div className="flex gap-4">
                <div className="text-[12px] font-medium text-[#5F6B7A] w-[60px] pt-0.5">09:42</div>
                <div className="flex-1">
                  <div className="text-[13px] font-semibold text-[#101828]">Semester 1 Fee Invoice Generated: ₹65,000</div>
                  <div className="text-[12px] text-[#5F6B7A]">Auto-generated by Finance Module</div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </section>
  );
}
