import { starterPost, type BlogPost } from './content-core';

export const STARTER_BLOG_POSTS_3: BlogPost[] = [
  starterPost({
    slug: "faculty-workload-planning-framework",
    title: "Faculty Workload Planning: A Transparent Institutional Framework",
    excerpt: "Plan teaching, advising, assessment, research and service responsibilities with clear assumptions and reviewable allocation decisions.",
    body: "Faculty workload planning should make responsibilities visible without reducing academic work to a single simplistic number. The framework needs agreed categories, transparent assumptions and a process for reviewing exceptions.\n\n## Define workload components\n\nTeaching contact, preparation, assessment, advising, research supervision, administration and service may all contribute. Define how each component is represented and where professional judgment is required.\n\n## Connect plans to actual assignments\n\nCourse offerings, section sizes, assessment patterns and supervision responsibilities should flow into the workload view. Avoid parallel spreadsheets that become disconnected from the academic schedule.\n\n## Review equity and feasibility\n\nDepartment leaders need to identify overload, under-allocation, concentrated assessment periods and unassigned responsibilities. Comparisons should account for role, discipline and approved adjustments rather than treating every activity as identical.\n\n## Preserve decision history\n\nChanges should show who approved them, why they were needed and which period they affect. This supports planning, reduces disputes and improves the next allocation cycle.\n\nA transparent framework helps leaders make better decisions while giving faculty a clear explanation of assigned responsibilities.",
    category: "People and HR",
    keywords: ["faculty workload planning", "teaching allocation", "academic workload", "higher education HR"],
    publishedAt: "2026-06-22T09:00:00.000Z",
    updatedAt: "2026-06-22T09:00:00.000Z",
    featured: false,
  }),
  starterPost({
    slug: "digital-student-identity-architecture",
    title: "Digital Student Identity Architecture for a Connected Campus",
    excerpt: "Create a secure identity foundation for portals, mobile access, services and credentials without duplicating authentication logic.",
    body: "A digital student identity should connect verified identity, institutional affiliation and current entitlements. It should not become a collection of unrelated accounts managed by each campus service.\n\n## Establish an identity source of truth\n\nDefine how a person is matched from applicant to student and later to alumnus. Stable identifiers, duplicate resolution and lifecycle status are essential before adding mobile credentials or service integrations.\n\n## Separate authentication from authorization\n\nAuthentication confirms who the user is. Authorization decides what that identity can do in the current institutional context. Services should consume approved identity and role claims rather than creating independent permission rules.\n\n## Manage the lifecycle\n\nAccess should change when a student enrolls, changes programme, takes leave, graduates or loses an entitlement. Time-bound and service-specific access must expire predictably.\n\n## Protect recovery and support\n\nAccount recovery is a high-risk workflow. Use verified channels, strong evidence, rate limits and audit history. Support staff should not need broad access to solve common identity issues.\n\nA connected identity architecture improves security and student experience because one verified lifecycle drives many approved services.",
    category: "Digital Campus",
    keywords: ["digital student identity", "campus identity management", "student portal security", "digital campus ID"],
    publishedAt: "2026-06-18T09:00:00.000Z",
    updatedAt: "2026-06-18T09:00:00.000Z",
    featured: false,
  }),
  starterPost({
    slug: "ai-governance-higher-education",
    title: "AI Governance for Higher Education: From Policy to Daily Control",
    excerpt: "Turn responsible-AI principles into approved use cases, data boundaries, human review, monitoring and accountable decisions.",
    body: "AI governance becomes useful when it changes how a proposed use case is approved, built, reviewed and monitored. A policy alone cannot decide whether a particular model should access student records or influence an institutional decision.\n\n## Classify the use case\n\nDocument the purpose, affected users, decision impact, data categories, model provider and expected human role. A low-impact drafting assistant requires different controls from a system that prioritizes student interventions.\n\n## Set data boundaries\n\nDefine what data may be used, where processing occurs, how prompts and outputs are retained and whether provider training is disabled. Sensitive or regulated data should not flow into a tool because it is convenient.\n\n## Preserve human accountability\n\nThe responsible institutional role must remain clear. AI output should be treated as a proposal, recommendation or draft where appropriate. High-impact actions need review, explanation and a route for correction.\n\n## Monitor real operation\n\nTrack approved use, failure patterns, overrides, complaints, drift and changes to the underlying provider. Reassess when the use case, data or model changes.\n\nUse the [CampusOS AI governance workspace](/ai-governance) to structure reviewable decisions rather than relying on informal tool adoption.",
    category: "AI Governance",
    keywords: ["AI governance higher education", "responsible AI university", "education AI policy", "AI risk management"],
    publishedAt: "2026-06-14T09:00:00.000Z",
    updatedAt: "2026-06-14T09:00:00.000Z",
    featured: true,
  }),
  starterPost({
    slug: "zero-trust-campus-cybersecurity",
    title: "Zero-Trust Principles for Campus Cybersecurity",
    excerpt: "Apply identity verification, least privilege, segmentation, device context and continuous review to complex higher-education environments.",
    body: "Higher-education environments combine open collaboration, diverse devices, changing populations and sensitive records. Zero-trust principles help reduce reliance on network location as proof of legitimacy.\n\n## Verify identity and context\n\nUse strong authentication for privileged and sensitive actions. Consider device posture, session risk and the requested resource. A valid password alone should not justify every action.\n\n## Enforce least privilege\n\nPermissions should reflect current responsibilities and scope. Temporary access needs an expiry. Privileged roles require stronger review, and inactive accounts should not remain available indefinitely.\n\n## Segment systems and data\n\nSeparate public services, administrative systems, research environments and sensitive records. Integrations should use narrow service identities and documented data flows instead of shared credentials.\n\n## Observe and respond\n\nCollect useful security events, define alert ownership and rehearse response. Logging without review does not create control. Include identity changes, unusual exports, repeated failures and privileged actions.\n\nZero trust is a continuing operating model. Begin with the highest-risk identities and data paths, then expand based on evidence and institutional capacity.",
    category: "Privacy and Security",
    keywords: ["campus cybersecurity", "zero trust university", "higher education security", "least privilege"],
    publishedAt: "2026-06-10T09:00:00.000Z",
    updatedAt: "2026-06-10T09:00:00.000Z",
    featured: false,
  }),
  starterPost({
    slug: "erp-data-migration-checklist",
    title: "ERP Data Migration Checklist for Higher-Education Institutions",
    excerpt: "Plan extraction, cleansing, mapping, rehearsal, reconciliation and cutover with clear ownership for every critical dataset.",
    body: "Data migration should prove that the new platform can support current operations and preserve required history. Moving rows between databases is only one part of the work.\n\n## Inventory and classify data\n\nList source systems, owners, volumes, quality issues, retention needs and target modules. Identify authoritative sources where the same information appears in several systems.\n\n## Define mapping and transformation\n\nDocument how identifiers, codes, statuses, dates and relationships change. Mapping decisions should be reviewable by business owners, not only technical teams.\n\n## Rehearse with realistic volumes\n\nRun multiple migrations before cutover. Measure duration, failures and manual corrections. Test application workflows using migrated records rather than validating files in isolation.\n\n## Reconcile and sign off\n\nCompare counts, totals, samples and critical relationships. Finance balances, enrollments, results and identity links require specific reconciliation rules. Record accepted differences and unresolved risks.\n\n## Plan cutover and rollback\n\nDefine freeze periods, final extraction, communication, verification and rollback decisions. Assign owners for each checkpoint.\n\nA migration is complete when responsible teams trust the new records and can explain how they were validated.",
    category: "Implementation",
    keywords: ["ERP data migration checklist", "student data migration", "university system migration", "data reconciliation"],
    publishedAt: "2026-06-06T09:00:00.000Z",
    updatedAt: "2026-06-06T09:00:00.000Z",
    featured: false,
  }),
];
