'use client';

import React from 'react';
import { CreditCard, Loader2, MessageCircle, RefreshCw, ShieldCheck, Smartphone } from 'lucide-react';

type Dashboard = {
  subscriptions: Array<{ tenant_id: string; channel: string; lifecycle: string; billing_mode: string }>;
  providerHealth: Array<{ provider_key: string; channel: string; status: string; tenant_id: string | null; lastCheckedAt: string | null }>;
  usage: Array<{ tenantId: string; channel: string; units: number; estimatedMinor: number; actualMinor: number | null }>;
  plans: Array<{ planKey: string; name: string; version: number; currency: string; smsUnitCostMinor: number; whatsappUnitCostMinor: number; effectiveFrom: string }>;
};

async function api(path: string, init?: RequestInit) {
  const response = await fetch(path, { cache: 'no-store', ...init });
  const body = await response.json().catch(() => ({})) as Record<string, unknown>;
  if (!response.ok) throw new Error(typeof body.error === 'string' ? body.error : 'Platform communication request failed.');
  return body;
}

export function PlatformCommunicationsConsole() {
  const [data, setData] = React.useState<Dashboard | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [busy, setBusy] = React.useState(false);
  const [message, setMessage] = React.useState<string | null>(null);
  const [pricing, setPricing] = React.useState({ planKey:'OMNICHANNEL_STANDARD', name:'Omnichannel Standard', monthlyBaseMinor:0, includedSmsUnits:0, includedWhatsappUnits:0, smsUnitCostMinor:0, whatsappUnitCostMinor:0 });
  const [activation, setActivation] = React.useState({ tenantId:'', channel:'SMS', pricingVersionId:'', billingMode:'PREPAID', initialUnits:0 });

  const load = React.useCallback(async()=>{setData(await api('/api/communications/platform/dashboard') as unknown as Dashboard);setMessage(null);},[]);
  React.useEffect(()=>{void load().catch((e)=>setMessage(e instanceof Error?e.message:'Unable to load platform communications.')).finally(()=>setLoading(false));},[load]);

  async function action(payload: Record<string, unknown>) {
    setBusy(true); setMessage(null);
    try { const result=await api('/api/communications/platform/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); await load(); return result; }
    catch(e){setMessage(e instanceof Error?e.message:'Platform communication action failed.');throw e;}
    finally{setBusy(false);}
  }

  if(loading)return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-blue-700"/></div>;
  if(!data)return <div className="p-8 text-sm text-red-700">{message||'Platform communications unavailable.'}</div>;

  return <div className="mx-auto max-w-[1450px] space-y-6 p-4 sm:p-6 lg:p-8">
    <header className="flex flex-col gap-4 border-b border-slate-200 pb-6 dark:border-slate-800 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-blue-700"><ShieldCheck className="h-4 w-4"/><p className="text-[10px] font-black uppercase tracking-[0.14em]">Platform communications</p></div><h1 className="mt-2 text-3xl font-black tracking-[-0.04em]">Provider, pricing & channel entitlements</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Manage SMS/WhatsApp products and provider health without exposing institution-private message bodies or student records.</p></div><button onClick={()=>void load()} className="inline-flex h-10 items-center gap-2 self-start rounded-xl border border-slate-200 px-4 text-xs font-extrabold dark:border-slate-700"><RefreshCw className="h-4 w-4"/>Refresh</button></header>
    {message&&<div className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs font-semibold text-slate-600 dark:border-slate-800 dark:bg-slate-900">{message}</div>}
    <div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Active subscriptions</p><p className="mt-3 text-3xl font-black">{data.subscriptions.filter(s=>s.lifecycle==='ACTIVE').length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Pricing plans</p><p className="mt-3 text-3xl font-black">{data.plans.length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Provider records</p><p className="mt-3 text-3xl font-black">{data.providerHealth.length}</p></div></div>
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center gap-2"><CreditCard className="h-4 w-4 text-blue-700"/><p className="text-sm font-extrabold">Create pricing version</p></div><p className="mt-1 text-[10px] text-slate-500">All monetary values are integer minor units. NAVEMORA does not hardcode commercial prices.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><input value={pricing.planKey} onChange={e=>setPricing({...pricing,planKey:e.target.value})} placeholder="Plan key" className="h-10 rounded-xl border border-slate-200 px-3 text-xs dark:border-slate-700 dark:bg-slate-900"/><input value={pricing.name} onChange={e=>setPricing({...pricing,name:e.target.value})} placeholder="Plan name" className="h-10 rounded-xl border border-slate-200 px-3 text-xs dark:border-slate-700 dark:bg-slate-900"/>{(['monthlyBaseMinor','includedSmsUnits','includedWhatsappUnits','smsUnitCostMinor','whatsappUnitCostMinor'] as const).map(key=><label key={key} className="text-[9px] font-bold uppercase tracking-wide text-slate-500">{key.replaceAll(/([A-Z])/g,' $1')}<input type="number" min="0" value={pricing[key]} onChange={e=>setPricing({...pricing,[key]:Number(e.target.value)})} className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-xs normal-case dark:border-slate-700 dark:bg-slate-900"/></label>)}</div><button disabled={busy} onClick={()=>void action({action:'create_pricing',...pricing})} className="mt-4 h-10 rounded-xl bg-blue-700 px-4 text-xs font-extrabold text-white disabled:opacity-50">Create pricing version</button></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center gap-2"><Smartphone className="h-4 w-4 text-blue-700"/><p className="text-sm font-extrabold">Activate paid institution channel</p></div><div className="mt-4 grid gap-3"><input value={activation.tenantId} onChange={e=>setActivation({...activation,tenantId:e.target.value})} placeholder="Institution tenant UUID" className="h-10 rounded-xl border border-slate-200 px-3 text-xs dark:border-slate-700 dark:bg-slate-900"/><div className="grid grid-cols-2 gap-2"><select value={activation.channel} onChange={e=>setActivation({...activation,channel:e.target.value})} className="h-10 rounded-xl border border-slate-200 px-3 text-xs dark:border-slate-700 dark:bg-slate-900"><option>SMS</option><option>WHATSAPP</option></select><select value={activation.billingMode} onChange={e=>setActivation({...activation,billingMode:e.target.value})} className="h-10 rounded-xl border border-slate-200 px-3 text-xs dark:border-slate-700 dark:bg-slate-900"><option>PREPAID</option><option>POSTPAID</option><option>INCLUDED</option><option>CUSTOM</option></select></div><input value={activation.pricingVersionId} onChange={e=>setActivation({...activation,pricingVersionId:e.target.value})} placeholder="Pricing version UUID (optional)" className="h-10 rounded-xl border border-slate-200 px-3 text-xs dark:border-slate-700 dark:bg-slate-900"/><input type="number" min="0" value={activation.initialUnits} onChange={e=>setActivation({...activation,initialUnits:Number(e.target.value)})} placeholder="Initial prepaid units" className="h-10 rounded-xl border border-slate-200 px-3 text-xs dark:border-slate-700 dark:bg-slate-900"/><button disabled={busy||!activation.tenantId} onClick={()=>void action({action:'activate_channel',...activation,pricingVersionId:activation.pricingVersionId||null})} className="h-10 rounded-xl bg-blue-700 px-4 text-xs font-extrabold text-white disabled:opacity-50">Activate channel</button></div></section></div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950"><div className="border-b border-slate-100 p-4 dark:border-slate-800"><p className="text-sm font-extrabold">Latest pricing</p></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{data.plans.map(plan=><div key={`${plan.planKey}:${plan.version}`} className="grid gap-3 p-4 md:grid-cols-[1fr_auto_auto]"><div><p className="text-xs font-extrabold">{plan.name}</p><p className="mt-1 text-[10px] text-slate-500">{plan.planKey} · v{plan.version} · effective {new Date(plan.effectiveFrom).toLocaleDateString()}</p></div><div className="text-right"><p className="text-xs font-black">{plan.currency} {(plan.smsUnitCostMinor/100).toFixed(2)}</p><p className="text-[9px] text-slate-500">SMS unit</p></div><div className="text-right"><p className="text-xs font-black">{plan.currency} {(plan.whatsappUnitCostMinor/100).toFixed(2)}</p><p className="text-[9px] text-slate-500">WhatsApp unit</p></div></div>)}{data.plans.length===0&&<p className="p-6 text-xs text-slate-500">No pricing has been configured. Paid channels should remain inactive.</p>}</div></section>
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950"><div className="border-b border-slate-100 p-4 dark:border-slate-800"><p className="text-sm font-extrabold">Provider health</p></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{data.providerHealth.map((p,i)=><div key={`${p.provider_key}:${i}`} className="flex items-center justify-between gap-4 p-4"><div><p className="text-xs font-extrabold">{p.provider_key}</p><p className="mt-1 text-[10px] text-slate-500">{p.channel} · {p.tenant_id?'Institution-managed':'Platform-managed'}</p></div><span className="text-[10px] font-black">{p.status}</span></div>)}{data.providerHealth.length===0&&<p className="p-6 text-xs text-slate-500">No configured provider health records.</p>}</div></section><section className="rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950"><div className="border-b border-slate-100 p-4 dark:border-slate-800"><div className="flex items-center gap-2"><MessageCircle className="h-4 w-4 text-blue-700"/><p className="text-sm font-extrabold">Institution subscriptions</p></div></div><div className="max-h-[420px] divide-y divide-slate-100 overflow-y-auto dark:divide-slate-800">{data.subscriptions.map((s,i)=><div key={`${s.tenant_id}:${s.channel}:${i}`} className="p-4"><div className="flex justify-between gap-4"><div><p className="text-xs font-extrabold">{s.channel}</p><p className="mt-1 font-mono text-[9px] text-slate-500">{s.tenant_id}</p></div><span className="text-[10px] font-black">{s.lifecycle}</span></div></div>)}</div></section></div>
  </div>;
}
